### ISSUE TITLE
Gros pack file

### ISSUE THREAD

**Issue by raf924** [ZiperRom1/web#4]
En reclonant le repo j'ai remarqué qu'il pesait 46Mo environ ce qui est trop, beaucoup trop. Après un petit du sur le dossier il m'est apparu que c'était à cause des packfiles, c'est-à-dire l'historique du repo qui contient les fichiers images et dmp que je t'avais fait supprimer. Je savais que ça allait causer des problèmes. Trouve un moyen pour t'en débarrasser.

**Comment by mister-good-deal** [comment]
Done, j'y suis allé en mode bourrin donc plus d'historique sur aucune branche :p
Par contre en fait je crois que c'était la branche gh-pages qui était foireuse et qui prenait 40 Mo ...
